add_newline = false

format = """
$cmd_duration ó°œ¥ $directory $git_branch
$character
"""

[character]
success_symbol = "[  î©± ï‹](bold fg:#ffffff)" # blue slot
error_symbol = "[  ï€ ï‹](bold fg:#ffffff)"   # red slot

[package]
disabled = true

[git_branch]
symbol = "ó°˜¬"
truncation_length = 12
truncation_symbol = ""
format = "ó°œ¥ [î‚¶](bold fg:6)[$symbol $branch(:$remote_branch)](fg:#ffffff bg:6)[î‚´ ](bold fg:6)"

[git_commit]
commit_hash_length = 4
tag_symbol = "ï’¶ "

[git_state]
format = '[\($state( $progress_current of $progress_total)\)]($style) '
cherry_pick = "[ğŸ’ PICKING](bold fg:#ffffff)"

[git_status]
conflicted = " ğŸ³ "
ahead = " ğŸğŸ’¨ "
behind = " ğŸ˜° "
diverged = " ğŸ˜µ "
untracked = " ğŸ¤· "
stashed = " ğŸ“¦ "
modified = " ğŸ“ "
staged = '[++\($count\)](fg:2)'
renamed = " âœï¸ "
deleted = " ğŸ—‘ "

[hostname]
ssh_only = false
format = "[â€¢$hostname](bg:6 bold fg:#ffffff)[î‚´](bold fg:#ffffff)"
trim_at = ".companyname.com"
disabled = false

[line_break]
disabled = false

[username]
style_user = "bold bg:6 fg:#ffffff"
style_root = "bold fg:#ffffff"
format = "[î‚¶](bold fg:#ffffff)[$user](bold fg:#ffffff)"
disabled = false
show_always = true

[directory]
home_symbol = " ï‘­ "
read_only = " ï‘– "
style = "bg:2 fg:#ffffff"
truncation_length = 6
truncation_symbol = " â€¢â€¢/"
format = '[î‚¶](bold fg:2)[ó°‰‹ $path](bold bg:2 fg:#ffffff)[î‚´](bold fg:2)'

[directory.substitutions]
"Desktop" = " ï’© "
"Documents" = " ï’¥ "
"Downloads" = " ï‰ "
"Music" = " ó°ˆ "
"Pictures" = " ï "
"Videos" = " ï”¬ "
"GitHub" = " ó°Š¤ "

[cmd_duration]
min_time = 0
format = '[î‚¶](bold fg:3)[ó°ª¢ $duration](bold bg:3 fg:#ffffff)[î‚´](bold fg:3)'

[battery]
disabled = false
format = '[ğŸ”‹ $percentage]($style) '
[[battery.display]]
threshold = 20
style = "bold fg:1"

